In [15]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:.6f}'.format
df = pd.read_csv('약국별속성최종본.csv',encoding='EUC-KR')

In [16]:
df_2 = df[df.columns[6:]]
col_lst=list(df_2.columns)

In [17]:
scaler = MinMaxScaler()
df_scaled_minmax=pd.DataFrame()
df_scaled_minmax[col_lst] =scaler.fit_transform(df_2)

In [18]:
df_scaled_minmax

,응급실개수,버스개수,지하철개수,편의점개수,심야약국개수,평균유동인구,평균생활인구수,경증환자_약품비,기타환자_약품비,전체환자_약품비,경증환자수,기타환자수,전체환자수,경증_약품비_비율,경증_환자수_비율,반경내_세대수_합,반경내_인구수_합,응급실_평균거리,버스_평균거리,지하철_평균거리,편의점_평균거리,심야약국_평균거리,동_생활인구_평균,동_유동인구_합,동_거주인구_합,반경내_생활인구_추정,bus_ratio,sub_ratio,store_ratio,emer_ratio,nd_ratio
0,0.000000,0.390244,0.000000,0.097561,0.000000,0.002958,0.641042,1.000000,0.931264,0.968391,1.000000,1.000000,1.000000,0.177809,0.350506,0.009669,0.008679,0.000000,0.499341,0.000000,0.452987,0.000000,0.641042,0.000387,0.004350,0.405519,0.428295,0.000000,0.113247,0.000000,0.000000
1,0.000000,0.365854,0.000000,0.097561,0.000000,0.002958,0.641042,1.000000,0.931264,0.968391,1.000000,1.000000,1.000000,0.177809,0.350506,0.009669,0.008679,0.000000,0.459613,0.000000,0.485426,0.000000,0.641042,0.000387,0.004350,0.405519,0.436234,0.000000,0.121357,0.000000,0.000000
2,0.000000,0.048780,0.000000,0.097561,0.000000,0.000000,0.641042,1.000000,0.931264,0.968391,1.000000,1.000000,1.000000,0.177809,0.350506,0.000259,0.000281,0.000000,0.779213,0.000000,0.388071,0.000000,0.641042,0.000387,0.004350,0.003185,0.034308,0.000000,0.097018,0.000000,0.000000
3,0.000000,0.292683,0.000000,0.073171,0.000000,0.002958,0.641042,1.000000,0.931264,0.968391,1.000000,1.000000,1.000000,0.177809,0.350506,0.015610,0.013438,0.000000,0.639762,0.000000,0.704874,0.000000,0.641042,0.000387,0.004350,0.459409,0.250717,0.000000,0.234958,0.000000,0.000000
4,0.000000,0.243902,0.000000,0.243902,0.000000,0.000029,0.641042,1.000000,0.931264,0.968391,1.000000,1.000000,1.000000,0.177809,0.350506,0.013980,0.015490,0.000000,0.604294,0.000000,0.742351,0.000000,0.641042,0.000387,0.004350,0.178375,0.221193,0.000000,0.074235,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5076,0.000000,0.707317,0.200000,0.073171,0.000000,0.043119,0.130573,0.166836,0.144972,0.135754,0.199112,0.099159,0.133947,0.418275,0.741308,0.265526,0.449112,0.000000,0.646556,0.758318,0.493653,0.000000,0.130573,0.002784,0.043190,0.333702,0.599532,0.025715,0.164551,0.000000,0.000000
5077,0.000000,0.365854,0.000000,0.487805,0.142857,0.083922,0.244525,0.355957,0.020010,0.071183,0.471935,0.107334,0.259650,1.000000,1.000000,0.355896,0.309438,0.000000,0.583261,0.000000,0.661076,0.866925,0.244525,0.007435,0.032173,0.449717,0.343755,0.000000,0.033054,0.000000,0.866925
5078,0.000000,0.292683,0.000000,0.536585,0.142857,0.148996,0.244525,0.355957,0.020010,0.071183,0.471935,0.107334,0.259650,1.000000,1.000000,0.387115,0.339238,0.000000,0.735009,0.000000,0.666096,0.932169,0.244525,0.007435,0.032173,0.624444,0.218227,0.000000,0.030277,0.000000,0.932169
5079,0.000000,0.219512,0.000000,0.097561,0.000000,0.110018,0.180371,0.292971,0.647565,0.582325,0.237621,0.465885,0.358899,0.053628,0.171167,0.147042,0.209997,0.000000,0.756120,0.000000,0.670236,0.000000,0.180371,0.003511,0.009451,0.839369,0.159101,0.000000,0.167559,0.000000,0.000000
5080,0.000000,0.585366,0.200000,0.195122,0.000000,0.032744,0.022116,0.295553,0.825769,0.731784,0.177878,0.559253,0.385294,0.000000,0.000000,0.112986,0.128182,0.000000,0.643941,0.690851,0.744321,0.000000,0.022116,0.001044,0.005214,0.260187,0.498179,0.028227,0.093040,0.000000,0.000000

In [8]:
df_scaled_minmax['잠재구매']= df_scaled_minmax['경증환자수']+\
df_scaled_minmax['경증환자_약품비']+ \
df_scaled_minmax['경증_약품비_비율']+ \
df_scaled_minmax['경증_환자수_비율']+ \
df_scaled_minmax['반경내_생활인구_추정']+\
df_scaled_minmax['평균유동인구']+\
df_scaled_minmax['반경내_인구수_합']

#가중치를 곱해줌
df_scaled_minmax['잠재구매지수']=df_scaled_minmax['잠재구매']*0.3

In [9]:
df_scaled_minmax['교통접근']= df_scaled_minmax['버스개수'] +\
df_scaled_minmax['지하철개수']+\
df_scaled_minmax['bus_ratio']+\
df_scaled_minmax['sub_ratio']

df_scaled_minmax['교통접근지수']=df_scaled_minmax['교통접근']*0.5

In [10]:
df_scaled_minmax['잠재경쟁']=df_scaled_minmax['store_ratio']+\
df_scaled_minmax['nd_ratio']+df_scaled_minmax['emer_ratio']+\
df_scaled_minmax['응급실개수']+\
df_scaled_minmax['심야약국개수']+\
df_scaled_minmax['편의점개수']

df_scaled_minmax['잠재경쟁지수']=df_scaled_minmax['잠재경쟁']*0.2

In [11]:
df_score = df_scaled_minmax.copy()

df_score = df_score[['잠재구매지수','교통접근지수','잠재경쟁지수']]

In [12]:
df_score['총점']=(df_score['잠재구매지수'])+ \
(df_score['교통접근지수'])+ \
(df_score['잠재경쟁지수'])
df_score['순위'] = df_score['총점'].rank(ascending=False)
df_score

       잠재구매지수   교통접근지수   잠재경쟁지수       총점          순위
0    0.883642 0.409270 0.042162 1.335073 2986.000000
1    0.883642 0.401044 0.043784 1.328469 3030.000000
2    0.759534 0.041544 0.038916 0.839994 4977.000000
3    0.901236 0.271700 0.061626 1.234562 3673.000000
4    0.816663 0.232548 0.063627 1.112838 4322.000000
...       ...      ...      ...      ...         ...
5076 0.705439 0.766282 0.047544 1.519266 1795.000000
5077 1.101290 0.354804 0.306128 1.762223  591.000000
5078 1.182171 0.255455 0.328378 1.766003  577.000000
5079 0.574431 0.189306 0.053024 0.816761 4989.000000
5080 0.268363 0.655886 0.057632 0.981881 4770.000000

[5081 rows x 5 columns]

In [13]:
df_fin = pd.concat([df[df.columns[0:6]],df_score],axis=1)
df_fin.sort_values('순위')

,이름,도로명주소,Latitude,Longitude,구이름,동이름,잠재구매지수,교통접근지수,잠재경쟁지수,총점,순위
4549,허브약국,서울특별시 마포구 마포대로 73,37.542398,126.948968,마포구,용강동,1.056048,1.194417,0.294405,2.544870,1.000000
2987,용약국,서울특별시 마포구 신촌로 102-1,37.554604,126.937384,마포구,대흥동,1.069104,0.898792,0.575113,2.543009,2.000000
3299,올리브약국,서울특별시 마포구 신촌로 88,37.555372,126.935365,마포구,서교동,1.082619,0.877056,0.572037,2.531712,3.000000
3286,더블유스토어연세약국,서울특별시 마포구 신촌로 92,37.555170,126.935668,마포구,서교동,1.078812,0.887816,0.564378,2.531006,4.000000
3324,하임온누리약국,서울특별시 마포구 도화길 43,37.541775,126.950256,마포구,도화동,0.998713,1.188171,0.315619,2.502503,5.000000
...,...,...,...,...,...,...,...,...,...,...,...
5028,우리약국,서울특별시 종로구 옥인길 32-5 (옥인동),37.581097,126.966786,종로구,청운효자동,0.265792,0.213545,0.049422,0.528759,5077.000000
3190,충신약국,서울특별시 종로구 율곡로 259 (충신동),37.574004,127.006823,종로구,종로5.6가동,0.255030,0.208408,0.062155,0.525593,5078.000000
1246,메디팜삼현약국,서울특별시 종로구 새문안로3길 15,37.571747,126.972319,종로구,사직동,0.183698,0.260393,0.056597,0.500688,5079.000000
5036,세이지약국,서울특별시 서대문구 이화여대길 52,37.566670,126.950314,서대문구,충현동,0.306193,0.120296,0.056181,0.482670,5080.000000
2871,글로리아약국,서울특별시 종로구 평창문화로 75,37.606820,126.969217,종로구,평창동,0.265622,0.150961,0.039777,0.456360,5081.000000

In [79]:
df_fin.to_csv('최종산출데이터.csv',encoding='euc-kr',index=False)